### ISSUE TITLE
requestData in paused state?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-record#100]
The current text says:

"If state is not recording throw an InvalidStateError DOMException and terminate these steps. "

When pause has been called, the state is "paused". It seems natual to allow the client to gather up the data previous to the pause while the pause is in effect.

**Comment by yell0wd0g** [comment]
IIUC, [Gecko implementation](https://github.com/mozilla/gecko-dev/blob/master/dom/media/MediaRecorder.cpp#L551) already allows for [`requestData()`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-requestdata) to be called in `pause` state, so I'll update the Spec and Chromium.

**Comment by yell0wd0g** [comment]
Landing the Spec patch since FF does what it should and is just Cr that doesn't.

**Comment by yell0wd0g** [comment]
FTR https://crbug.com/673965 / https://crrev.com/2571093002
