### ISSUE TITLE
Odd overriding of bitrate parameters

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-record#101]
The current text says about BitsPerSecond parameter:

This parameter overrides either audioBitsPerSecond or videoBitsPerSecond if present

"Overrides" normallly means "totally renders them powerless".

It seems natural to say things like { bitrate: 4M, audioBitsPerSecond: 128k }
to indicate that a certain bitrate should be set aside for audio, while video can fill the rest.
OTOH, in

{bitrate: 4m, audio: 1m, video: 5m}

bitrate will clearly render the desired video bitrate null and void.
Should it instead say that bitsPerSecond is capping the sum of the audio + video bitrates?

**Comment by yell0wd0g** [comment]
`bitsPerSecond` reads now:
> Aggregate target bits per second for encoding of all Video and Audio Track(s) present. This parameter will limit either audioBitsPerSecond, videoBitsPerSecond or their sum, whichever is present, and might be distributed among the present track encoders as the UA sees fit. This parameter is a hint for the encoder(s) and the total value might be surpassed, not achieved, or only be achieved over a long period of time.
