### ISSUE TITLE
BlobEvent constructor arguments are missing

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#11]
http://w3c.github.io/mediacapture-record/MediaRecorder.html#blob-event

As a consequence, the BlobEventInit dictionary is unused in the spec.

**Comment by yell0wd0g** [comment]
Closing this issue per https://github.com/w3c/mediacapture-record/pull/25.

**Comment by yell0wd0g** [comment]
Also this guy https://github.com/w3c/mediacapture-record/pull/37.
