### ISSUE TITLE
Add a `MediaRecorderOption` to force a given source video frame rate

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#113]
This would allow `conforming` by forcing the timestamps of the container to be generated at a certain frame rate, versus the normal way of following the wall clock which somehow resembles the real time production.  This would allow e.g. shooting at 120fps but forcing a recording at, say, 30fps, which will produce a slo-mo video at 4x speed.  I propose adding a parameter to [`MediaRecorderOptions`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#mediarecorderoptions-section).

I like specifying the frame rate itself versus e.g. a multiplication/division factor so that it's not depending on the input frame rate, which might be flaky, e.g. with changes in illumination.

**Comment by yell0wd0g** [comment]
@pehrsons I'm interested to hear your opinion here (or in the PR).

**Comment by rociom** [comment]
Haha
