### ISSUE TITLE
Address comments from TAG review

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-record#115]
See https://github.com/w3ctag/spec-reviews/issues/131:
> One other thought from me is that the examples could use a little more prose. For example, in the second example:
>  *  how does the video element relate to what's going on?
>  * what controls the object lifetimes, i.e., when does the MediaRecorder become GC-able?
>
> We're still interested in seeing work using ReadableStream here, perhaps as a return value from start().

**Comment by yell0wd0g** [comment]
Added literature to the examples.
Use of Streams for recording is tracked in  #87
