### ISSUE TITLE
Enable transparency channel support

### ISSUE THREAD

**Issue by spereirag** [w3c/mediacapture-record#116]
It would be quite useful to have the possibility to capture streams containing a transparency channel. Right now if one tries to record a canvas with RGBA values, the resulting stream will contain only the RGB values, completely opaque.

[Here's a related stackoverflow post.](http://stackoverflow.com/questions/42146396/capture-video-with-alpha-channel-using-canvas-capturestream)

**Comment by yell0wd0g** [comment]
Yeah, I was discussing this and other related problems (e.g. what about 16bpp single alpha channels like in the depth capture) recently. MediaRecorder spec-wise should record any content coming through a Media Stream Track, including any alpha channel (which I believe can only come from a `<canvas>.captureStream()` now).  I would say this is an issue of the implementors, i.e. Chrome and Firefox, could you please file a bug (e.g. https://crbug.com/new and repost the bug number here so I can route it)?

**Comment by yell0wd0g** [comment]
Actually I already went ahead and filled in https://crbug.com/690968 :smile: since it's an interesting situation.  Thanks for reposting SO to here!
