### ISSUE TITLE
Should stop(), pause(), resume() change state synchronously?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-record#123]
With the exception of [start()](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-start), which sets `state` to `"recording"` synchronously, all the other state-changing methods, stop(), pause(), resume(), set `state` asynchronously, in the queued task that fires the corresponding event.

Do we have a good reason for this? I'm asking because both Chrome and Firefox appear to set `state` synchronously, and fire the event asynchronously. Try it [here](https://jsfiddle.net/jib1/tmufhavj/).

We're [adding `pause` and `resume` events to Firefox](https://bugzil.la/1363915), and aren't sure what to do.

Full disclosure: I fixed the start() method in https://github.com/w3c/mediacapture-record/pull/56. The spec seemed confused about this before then, throwing exceptions in queued tasks.

cc @foolip, @SingingTree

**Comment by foolip** [comment]
When the actual state isn't synchronously available, then I think there are two options for methods and setters that affect state:
* Pretend that the state changes synchronously anyway, and queue a task to fire events. Media elements mostly work like this.
* Instead wait for the real change to complete, and change the state + fire the event at the same time once done. It means one has to deal with different operations racing to complete, or have a queue of operations.

It sounds like there's a mix here, and that it's mostly async. So perhaps best to make everything async. If you ever want these methods to return promises, that'll make more sense too. (When done: change state, resolve promise, fire event.)

**Comment by yell0wd0g** [comment]
So @jan-ivar , @foolip: IIUC the proposal is to make all state transitions asynchronous, which will need modifying the literature of `start()` and adapting the Cr and FF code, correct?

**Comment by foolip** [comment]
I don't have much skin in the game, but yeah, if it seems likely to be web compatible, then going full async seems reasonable.

**Comment by jan-ivar** [comment]
Well, the most web compatible would of course be changing the spec to match Chrome and Firefox. 

Clearly some code would break from this, the question is how much code would break.

For instance, my own [fiddle](http://jsfiddle.net/jib1/tmwLxjLy/) should work, except I apparently do this for debug reasons:
```js
rec.start();
log(rec.state + " for "+ (ms / 1000) +" seconds..."); // recording for 5 seconds
```
which would now say "inactive for 5 seconds" 😜

Sure that's probably unusual, but why did I do this? Probably a form of defensive programming, to get feedback and catch bugs early. I could see others writing JS defensively, not exactly like this, but using assert-like throws to catch the runtime deviating at all from the expectations the developer clung to when they wrote their code.

**Comment by foolip** [comment]
If it's at all likely that any content depends on this, then I think the options are:
1. Leave it as it and add a comment saying that it's a historical accident
2. Measure how often `state` is accessed in the interim where it would change before deciding whether to change the spec.

**Comment by jan-ivar** [comment]
@foolip Since "as is" is that the spec does not match implementations, except for `start()`, aren't the options:

   1. Fix remaining spec methods to set state synchronously + comment that it's a historical accident
   2. Measure how often state is accessed in the interim where it would change before deciding whether to fix `start` method to be async like the rest, and fix implementations.

?

I've had this in the back of my mind for a while, and I think I'm leaning toward this:

> Pretend that the state changes synchronously anyway, and queue a task to fire events. Media elements mostly work like this.

I think it should lead to fewer races in practice. Except for `"inactive"`, all [state](https://w3c.github.io/mediacapture-record/MediaRecorder.html#enumdef-recordingstate) is caused by JS methods anyway. In the case where a recording ends or terminates because of failure, it seems like we can resolve races in the task queued to set state to `"inactive"`, by basically flushing anything that went before as belonging to the recording that just terminated.

Not seeing much practical benefit of going full async at this point. Even if we have the methods return promises, we'd still need to resolve races somehow, either like this, or using a queue of some sort.

Common usage wouldn't see any difference:
```js
await rec.start();
log(rec.state + " for "+ (ms / 1000) +" seconds..."); // recording for 5 seconds
```

Btw, when looking at the async steps in the spec, please see https://github.com/w3c/mediacapture-record/issues/131, which I just filed.

**Comment by foolip** [comment]
Sorry, I misspoke, by "as is" I meant whatever is actually interoperably implemented, not what the spec says.

The "pretend that the state changes synchronously" route seems OK if other implementers (not me) want it too.

Note that for media elements, the true async nature can still be observed, e.g. calling `pause()` makes the element look paused, but currentTime will change at least once more since the playback doesn't happen on the main thread. Are there situations like that here?

**Comment by jan-ivar** [comment]
> currentTime will change at least once more

@foolip In Chrome yes, in Firefox no.  - https://jsfiddle.net/jib1/r79L3j05/

I don't know the playback specs well enough to comment on which is correct, but I do know neither browser allows `currentTime` to observably advance during the current run of the event loop, so the time that JS sees seems well under browser control here.

As to whether media recorder might have similar situations, dunno. @SingingTree may know our implementation better here, but last I checked we did more things here synchronously than I expected, which is a different problem, but we may not have the problem you mentioned.

**Comment by SingingTree** [comment]
I believe we can run into the issue alluded to above:

> Note that for media elements, the true async nature can still be observed, e.g. calling pause() makes the element look paused, but currentTime will change at least once more since the playback doesn't happen on the main thread. Are there situations like that here?

Data is delivered to our encoders on a different thread than the one we control the recorder on. As it stands I think we could end up with a race between delivery and control functions.

**Comment by SingingTree** [comment]
I've created a fiddle to test record/resume drift on a changing colour canvas: https://jsfiddle.net/SingingTree/ykv6rj4v/ Right now in Firefox I see issues with blue being recorded, which I believe indicates the type of issue mentioned above

**Comment by jan-ivar** [comment]
@SingingTree Thanks! That fiddle seems like a good use-case for what people might want to do with `pause()`. Chrome seems to only record green, so I'm hoping we can fix Firefox here.

**Comment by jan-ivar** [comment]
We're finally adding this in Firefox 65, modulo [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1514016), and based on https://github.com/w3c/mediacapture-record/issues/123#issuecomment-324881548 have decided to follow Chrome, for webcompat reasons.

I'll add a PR here to this effect, for consideration. @yellowdoge @foolip PTAL.
