### ISSUE TITLE
Make stop() idempotent.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-record#125]
Currently, the [spec](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-stop) says
```js
rec.stop();
rec.stop();
```
must throw an `InvalidStateError`. This seems inconsistent with e.g. `track.stop()` (https://github.com/w3c/mediacapture-main/issues/459) and `pc.close()` (https://github.com/w3c/webrtc-pc/commit/3c3fbb324f305eec85f81a6f468e450c26ebd7bd).

**Comment by yell0wd0g** [comment]
To round up the info, [chrome](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/mediarecorder/MediaRecorder.cpp?q=mediarecorder.cpp&sq=package:chromium&dr&l=232) and [firefox](https://github.com/mozilla/gecko-dev/blob/master/dom/media/MediaRecorder.cpp#L1093) seem to be throwing if the state is `inactive`, so we'd need to change both accordingly.

What would be the rationale for changing this behaviour from throwing to, essentially, ignoring? 

What would the correct action be in methods such as [`pause()`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-pause), [`resume()`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-resume) etc, where we also check that the state is not `inactive`?

**Comment by jan-ivar** [comment]
pause() and resume() are already idempotent in the spec. I.e.
```js
rec.start();
rec.pause();
rec.pause();
rec.resume();
rec.resume();
```
does not throw according to the spec and Chrome (Firefox throws `InvalidStateError`). See [fiddle](https://jsfiddle.net/jib1/9xdzcfer/).

My rationale for `stop()` being idempotent as well is that otherwise the above fiddle would behave unexpectedly and sometimes throw, if, instead of a camera, the source were e.g. a video file of finite length. Basically, it would throw if the video file's duration was <6 seconds, and not throw if it was >6 seconds. Basically `ended` racing with `stop()`.

**Comment by yell0wd0g** [comment]
Hmm I guess I see the point. Could you please make a PR with the updated literature? 

It'd be interesting to add an example with those transitions stated explicitly and explained (and a link to some fiddle?), to exemplify what we mean with this.

**Comment by jan-ivar** [comment]
Note the examples I use here would also be affected by whatever we decide in https://github.com/w3c/mediacapture-record/issues/123.

**Comment by jan-ivar** [comment]
https://github.com/w3c/mediacapture-record/pull/158 was merged, so I think this one can be closed actually.
