### ISSUE TITLE
Where to file a new issue, here or in the W3C Bugzilla?

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#13]
I filed 4 issues:
- Bug 29102 - MediaStream Recording API: remove RecordingErrorNameEnum and use DomException instead.
- Bug 29103 - MediaStream Recording API: MediaRecorderErrorEvent is a NoInterfaceObject, consider removing
- Bug 29104 - BlobEvent is defined in both MediaStream Recorder and MediaStream ImageCapture, consider factoring them out.
- Bug 29105 - MediaStream Recording API: Consider not using BlobEvent, using Blob and FileReader instead

that aroused during code review of the implementation of this API for Chromium
(http:/crrev.com/1255873002/).

**Comment by alvestrand** [comment]
They should be filed here.

The bugzilla bugs have been filed against the Streams API, which is the wrong specification.
Please refile.

**Comment by yell0wd0g** [comment]
With pleasure.
