### ISSUE TITLE
How to concatenate Blobs of recordings into single file capable of playback?

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-record#130]
When recording for example each 1 second of a 60 second video using `HTMLMediaElement.captureStream()` and `MediaRecorder`, when we concatenate the discrete `Blob`s to a single `Blob` the resulting `Blob URL` created with `URL.createObjectURL()` only plays 1 second of media.

How to concatenate `Blob` objects having `MIME` type set to `video/webm` into a single `Blob`  capable of playback of all of the `Blob`s at `HTMLMediaElement`?

**Comment by legokichi** [comment]
```
const webm = blobs.reduce((a, b)=> new Blob([a, b], {type: "video/webm"}));
```

**Comment by guest271314** [comment]
@legokichi That concatenates the `Blob` objects, though does not render playback of concatenated `Blob`s beyond 1 second

**Comment by yell0wd0g** [comment]
Can you post some example code plz? Are you trying to merge individual 1s files?

**Comment by guest271314** [comment]
@yellowdoge Current code http://plnkr.co/edit/dNznvxe504JX7RWY658T?p=preview version 1 using `Blob URL`, version 2 using `MediaSource` evolved from https://github.com/guest271314/OfflineMediaContext, see also https://github.com/whatwg/html/issues/2824. 

In the interim tried `mkvmerge -o output.webm -w file1.webm + file2.webm` at `terminal` following [Joining webm videos under Linux](https://superuser.com/q/421130/) though error was logged

```
No append mapping was given for the file no. 1 ('file1.webm'). A default mapping of 1:0:0:0 will be used instead. Please keep that in mind if mkvmerge aborts with an error message regarding invalid '--append-to' options.
Error: The track number 0 from the file 'file2.webm' cannot be appended to the track number 0 from the file 'file1.webm'. The track parameters do not match.
```
Both `file1.webm` and `file2.wemb` were created using `MediaRecorder`.

**Comment by guest271314** [comment]
@yellowdoge  The basic concept is to be able to 1) create discrete files from media fragments, for example, 1 second of a video file, capable of independent playback; whether the implementation be `MediaRecorder` or other methods available at modern browsers; 2) the capability to concatenate or mix the independent media fragments into a single media file, where the media fragments may or may not be derived from the same original media resource

**Comment by guest271314** [comment]
@yellowdoge  Yes, trying to merge 60 1 second files into a single file.

**Comment by yell0wd0g** [comment]
I'm afraid that from the POV of Media Recorder there's not much that can be done since every one of these individual 1-second files would have a file header, several video frame headers and possibly a trailer; merging them would not be trivial at all.  

You could try wrapping e.g. [`mkvmerge`](https://mkvtoolnix.download/doc/mkvmerge.html) to in js using [emscriptem](http://kripken.github.io/emscripten-site/) or [WebAssembly](http://webassembly.org/), or perhaps cast each file in succession into a `<video>`/`<canvas>` and record a MediaStream out of it (see e.g. [`captureStream()`](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/external/wpt/mediacapture-fromelement/capture.html?type=cs&q=layouttests+capturestream+mediarecorder&sq=package:chromium&l=19)).

**Comment by guest271314** [comment]
@legokichi @yellowdoge See https://github.com/w3c/mediacapture-record/issues/132

**Comment by guest271314** [comment]
@legokichi Your solution at https://github.com/legokichi/ts-ebml/issues/2#issuecomment-294293842 appears to be a possible solution for https://github.com/w3c/media-source/issues/191. Have no experience using `TypeScript`. How to use code at https://jsfiddle.net/ub2jej7c/ to pass `Blob` or `MediaStream` to get seekable media?

**Comment by legokichi** [comment]
@guest271314 
https://github.com/legokichi/ts-ebml/issues/14#issuecomment-325200151

**Comment by jtheisen** [comment]
@yellowdoge Bizarre. Seems like a significant design flaw to me.

**Comment by guest271314** [comment]
> I'm afraid that from the POV of Media Recorder there's not much that can be done since every one of these individual 1-second files would have a file header, several video frame headers and possibly a trailer; merging them would not be trivial at all.

@yellowdoge Given that all of the input files were created by `MediaRecorder` cannot the raw data (audio and video content without headers) be extracted from the `.webm` files and written to a new `.webm` file?

**Comment by shallfer7** [comment]
Is this issue solved ? I've been facing this same problem.

**Comment by LucaGianni** [comment]
I had this exact issue and was able to resolve it by using [RecordRTC](https://recordrtc.org/)

It uses `MediaRecorder` and has pretty much the same syntax, however the `blob` returned by `ondataavailable` is different. With `MediaRecorder`, each `blob` contained header information (as discussed in previous comments here) which prevented concatenation, meaning the final video would stop playing after 1-2 seconds. 

However, each `blob` returned by `RecordRTC` after the first one seems to have these headers filtered out, meaning concatenation is very simple, e.g.
```
let blobs = [];
ondataavailable: (blob) => {
    blobs = [...blobs, blob];
}
// Concatenate blobs
let fullVideoBlob = new Blob(blobs, {'video/mp4'})
```
Hope this helps anyone looking for a solution to this issue!

**Comment by dosentmatter** [comment]
`MediaRecorder`, [`RecordRTC`](https://github.com/muaz-khan/RecordRTC), and [`MediaStreamRecorder`](https://github.com/streamproc/MediaStreamRecorder) blobs looks like they should be concatenatable as long as they are part of the same recording from a single instance as the headers are created only once. But it looks like the [example code](https://plnkr.co/edit/dNznvxe504JX7RWY658T?p=preview&preview) in https://github.com/w3c/mediacapture-record/issues/130#issuecomment-317137257 uses multiple `MediaRecorder` instances with `.start()` and `.stop()` which would create multiple blobs with headers in each blob(). These blobs would all be standalone video files and can't be concatenated simply by appending the bytes.

But maybe you can try using a single `MediaRecorder` instance with `pause()` and `resume()`.

See:
https://stackoverflow.com/a/75240595/7381355
https://github.com/muaz-khan/RecordRTC/issues/267#issuecomment-305697391
https://github.com/muaz-khan/RecordRTC/issues/539#issuecomment-511367790
