### ISSUE TITLE
Promise version of requestData?

### ISSUE THREAD

**Issue by saschanaz** [w3c/mediacapture-record#137]
Currently an author has to add an event listener first and then call `requestData` to get the recorded blob. I think its use can be easier if it returns a Promise that resolves when the data becomes available.

It currently unfortunately throws synchronously so it probably cannot return Promise as it is. What do you think?

**Comment by alvestrand** [comment]
The model of recording with record.start(non-null) is that you get a series of chunks. In the promise model, what happens to the second chunk?
It seems complex to me to ask the user to handle two completely different methods of operation of the API.

**Comment by dontcallmedom** [comment]
Given that `requestData` can happen multiple times, and per the [TAG guidance on the topic](https://www.w3.org/2001/tag/doc/promises-guide#recurring-events), promises wouldn't be a good fit, so closing.
