### ISSUE TITLE
Spec refers to "isolation properties" but this term is never explained

### ISSUE THREAD

**Issue by a2sheppy** [w3c/mediacapture-record#138]
The spec mentions in a couple of places (https://w3c.github.io/mediacapture-record/MediaRecorder.html#mediarecorder-methods) "stream's isolation properties" when describing security errors, but doesn't explain what these isolation properties are. Is there an actual property on an interface somewhere that's being referenced here? Or is this about general concepts like same-origin or whatever?

The `captureStream()` spec includes an `"origin-clean"` property. Are we talking about something similar here?

At a minimum, the MediaStream Recording spec needs to point to a definition of what this term refers to. Otherwise it needs to actually define it. Without that, the scenarios in which security errors are not necessarily obvious.

**Comment by stefhak** [comment]
I expect that was is meant is the concept of 'Isolated Media Streams" from webrtc-pc https://w3c.github.io/webrtc-pc/#isolated-media-streams

I think that can be made clearer.

**Comment by a2sheppy** [comment]
Ah-ha! I searched and searched but did not think to insert "media" into my searches. I kept searching for "isolated" and "isolated streams" and couldn't find anything, across three or four different specs. Yes, I think that's likely what's meant. Using the exact same name and including a reference link would be helpful.
