### ISSUE TITLE
Remove RecordingErrorNameEnum and use DomException instead

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#14]
The said RecordingErrorNameEnum [1] should not exist stand alone,
since it partially overlaps DomException [2], concretely 
INVALID_STATE_ERR and SECURITY_ERR. Reuse DomException.

[1] http://www.w3.org/TR/mediastream-recording/#MediaRecorderErrorEvent
[2] http://www.w3.org/wiki/DOM/domcore/DOMException

**Comment by beverloo** [comment]
This also goes for RecordingExceptionEnum, which defines "UnsupportedOption". A NotSupportedError DOMException should be used instead.

**Comment by yell0wd0g** [comment]
Filed https://github.com/w3c/mediacapture-record/issues/18 for RecordingExceptionEnum::UnsupportedOption.

**Comment by yell0wd0g** [comment]
Actually please ignore [1] and use [2] instead (the former is gone).

[1] http://www.w3.org/wiki/DOM/domcore/DOMException
[2] http://www.w3.org/TR/2015/WD-dom-20150618/#exception-domexception

**Comment by foolip** [comment]
I would probably suggest firing a simple error event, and adding a `readonly attribute DOMException error` to the MediaRecorder interface instead. This is how [`HTMLMediaElement`](https://html.spec.whatwg.org/multipage/embedded-content.html#media-elements) and [`IDBRequest`](http://w3c.github.io/IndexedDB/#request-api) etc. do similar things.

**Comment by yell0wd0g** [comment]
Can you have a look at https://github.com/w3c/mediacapture-record/pull/29 and let me know if this is closer/farther to a satisfactory conclusion? Happy to iterate.

**Comment by yell0wd0g** [comment]
Ok, let's forget about https://github.com/w3c/mediacapture-record/pull/29 in favour of first tackling the DOMExceptions and then the Error Events.

Let's concentrate the Error Event conversation in bug https://github.com/w3c/mediacapture-record/issues/31, if you guys don't mind.
