### ISSUE TITLE
Links to codepen examples?

### ISSUE THREAD

**Issue by rtoy** [w3c/mediacapture-record#144]
Should the spec really have links to codepen for some of the examples?  Even though the links are notes, linking to random sites unaffiliated with this spec or the W3C seems not good.  Maybe replace these links with links to the Wiki available here?

**Comment by yell0wd0g** [comment]
@rtoy what would you suggest instead of codepen? I.e. where in the "Wiki" would those go, do you have any examples?

**Comment by rtoy** [comment]
It would be nice if w3c.org had something, but you could just put it somewhere in https://github.com/w3c/mediacapture-record/wiki.

It just seems odd for the spec to have examples in locations not affiliated with the w3c or this repo.

WebAudio has [one design note on it's wiki.](https://github.com/WebAudio/web-audio-api/wiki/Design-cancelScheduledValues-and-hold).  We also have https://github.com/GoogleChromeLabs/web-audio-samples/wiki with some random notes about changes.  But none of these are linked to from the WebAudio spec.

**Comment by yell0wd0g** [comment]
The wiki only supports markdown IIUC, so the point of having a live demo would be lost. I could add it to my `pages` or some kind of personal repository but then we'd be out of the W3C again . 

> WebAudio has one design note on it's wiki.. 

In this WebAudio link, the first entry [CompositeAudioNode](https://github.com/GoogleChromeLabs/web-audio-samples/wiki/CompositeAudioNode) has a [Live Demo](http://jsbin.com/tevoba/edit?js,console) that links to a JSBin URL, is JSBin somehow W3C-friendlier than CodePen?

**Comment by rtoy** [comment]
I think the difference is that the WebAudio spec doesn't link to these pages from the spec.

I don't have any real solution to this. I just thought it odd to link to stuff in the spec that aren't somehow parts of w3c or the github repo.

Feel free to close this issue.

**Comment by rtoy** [comment]
I think the difference is that the WebAudio spec doesn't link to these pages from the spec.

I don't have any real solution to this. I just thought it odd to link to stuff in the spec that aren't somehow parts of w3c or the github repo.

Feel free to close this issue.
