### ISSUE TITLE
MediaRecorderErrorEvent is a NoInterfaceObject, consider removing

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#15]
MediaRecorderErrorEvent [1] idl says it's  NoInterfaceObject,
consider removing it.

[1] http://www.w3.org/TR/mediastream-recording/#MediaRecorderErrorEvent

**Comment by beverloo** [comment]
See https://heycam.github.io/webidl/#NoInterfaceObject.

> The [NoInterfaceObject] extended attribute should not be used on interfaces that are not solely used as supplemental interfaces, unless there are clear Web compatibility reasons for doing so. Specification authors who wish to use this feature are strongly advised to discuss this on the public-script-coord@w3.org mailing list before proceeding.

**Comment by yell0wd0g** [comment]
Peter@ can you take a look at the patch and close this issue if you're happy? Thx

**Comment by beverloo** [comment]
Yup, looks great! :) Thanks.

(I can't close the issue, however.)
