### ISSUE TITLE
Not clear if onpause/onresume should not be fired if it is already paused/recording

### ISSUE THREAD

**Issue by kbumsik** [w3c/mediacapture-record#150]
Hi, I'm currently fixing Firefox that does not actually fire any onpuase/onresume events.

While fixing code, I noticed that the spec does not make it clear if `pause()`/`resume()` has to simply return `undefined` without firing an event, when its `state` is already `paused`/`recording`? Allowing them fire an event would cause duplicated events.

FYI, Chrome returns undefined at the very beginning when it is already paused/recording state.

**Comment by alvestrand** [comment]
The spec as written clearly says that calling "pause(); pause()" must queue two tasks, both of which fire the "paused" event.

My immediate thought is that this seems silly. Should we change it?
(If we change it, the check for the paused state must be inside the queued task (otherwise race conditions could occur), so we can't let pause() return an error.)

**Comment by kbumsik** [comment]
Allowing only one "paused" event fired makes sense to me too.
> the check for the paused state must be inside the queued task.

I don't know much about implementation details but I'm wondering if it is trivial/common practice? As mentioned in #123, Firefox and Chrome currently change `state` synchronously, [so preventing multiple "paused" event is as easy as adding a single if statement...for now](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/mediarecorder/media_recorder.cc?l=278).

Currently Chrome does not fire multiple "paused" event, and Firefox (as my fix to add `onpause`/`onresume` is just accepted by the Firefox devs) fires multiple "paused"/"resume" events. Aside from the state transition being async, if W3C prefers only one "pause" event fired I can submit to patch to Firefox.

**Comment by Pehrsons** [comment]
I agree changing this makes sense. Note that this is affected by #157. CC @jan-ivar

**Comment by jan-ivar** [comment]
This should be quite easy to fix once https://github.com/w3c/mediacapture-record/pull/157 has merged.

**Comment by jan-ivar** [comment]
I'll provide a PR.

**Comment by jan-ivar** [comment]
Actually, I think I need to fix this in https://github.com/w3c/mediacapture-record/pull/157 itself.

**Comment by yell0wd0g** [comment]
Fixed by #157, do we/ should we have a WPT covering this?

**Comment by jan-ivar** [comment]
Thanks @yellowdoge! wpt test is set to arrive from [bug 1514016](https://bugzilla.mozilla.org/show_bug.cgi?id=1514016#c9).
