### ISSUE TITLE
Should a dataavailable event be dispatched in case there is no available data

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-record#153]
The current spec seems to mandate that a dataavailable event is sent even though there might be no data.
The current behavior is probably to dispatch such event with a blob whose size is 0.
Implementations might call WebSocket.send or upload empty blobs for no good reason though.
Or they would need to check the size of the blob, in which case having a nullable blob might make more sense.

Would it make sense to do the following:
- Return promises to notify the application that an action (stop/pause/requestData...) is done
- Dispatch dataavailable events only when needed if there is actually some data available

**Comment by yell0wd0g** [comment]
The UA might still fire `onDataAvailable` events with a `Blob` of size 0 if there is no new available encoded+multiplexed data -- this might happen if the user calls `requestData()` explicitly, or if the `|timeslice|` parameter supplied to `start()` is too small. JS code in my experience checks for blob size zero routinely.

**Comment by youennf** [comment]
I think we should probably go further and try using streams instead of blobs and events.
I'll file an issue for that.

**Comment by youennf** [comment]
Filed https://github.com/w3c/mediacapture-record/issues/154

**Comment by youennf** [comment]
> The UA might still fire `onDataAvailable` events with a `Blob` of size 0 if there is no new available encoded+multiplexed data -- this might happen if the user calls `requestData()` explicitly, or if the `|timeslice|` parameter supplied to `start()` is too small. JS code in my experience checks for blob size zero routinely.

For requestData, it probably makes sense to mandate such event.
For the other cases, I am wondering whether web apps will break if we decide to not fire such events when there is no data. @yellowdoge, wdyt?

That would allow two things:
- Applications not using requestData will no longer need this if check
- Browser will not have to create these blobs (creating a blob might trigger unnecessary overhead like IPC).

**Comment by yell0wd0g** [comment]
Apologies for the delay. I don't see an issue with having 0-sized blobs for the reason I gave before. The if-check is a hack I added while developing the Chrome code a long time ago, and somehow it has stuck around. Usually JS code will keep an array of `blobs` received on `onDataAvailable` and eventually concatenate those at a certain point in time for download; having a (number of) empty `blobs` won't make a difference.

> - Applications not using requestData will no longer need this if check

Like I said, the check is not needed :-)

Closing to simplify the issues accountancy; please shout if you disagree.
