### ISSUE TITLE
Use streams instead of blobs/events

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-record#154]
Blobs and events are not very convenient to use.
For instance, events are main thread only.
Blobs are not great if you want to concatenate them before sending them to the network.

**Comment by youennf** [comment]
In addition to promisifying start/stop/pause/resume, that could mean:
- Remove timeslice parameter
- Remove ondataavailable event
- Add a ReadableStream attribute (named data?)
For requestData, it might mean either removing it or renaming it to something like flushData.

**Comment by padenot** [comment]
I agree. However it would be more elegant to have symmetrical and WhatWG Stream based encoding and decoding API for audio and video.

Being able to pipe a `MediaStream` into an object and get a `ReadableStream` of encoded media out of it would be nice. Similarly, being able to write encoded media to a `WriteableStream` hooked up to a object that would also be tied to a clock domain, and get a `MediaStream` out of it would be nice. We could also get PCM audio or frames out of this object I suppose.

**Comment by youennf** [comment]
For decoding, it can somehow be implemented with SourceBuffer.appendStream() + video element + captureStream(). Agreed it is rather convoluted. At the same time, MediaStream is mostly useful right now for peer connections and video elements.
Unification of incoming media processing between MSE and WebRTC would be nice.

**Comment by padenot** [comment]
More importantly, there are no latency guarantees with this construct. We are probably going to propose something either in the Audio WG or the Media WG that is being discussed at the moment.

**Comment by yell0wd0g** [comment]
#87 is about the same integration, and we agreed to leave to v 2.0 of the Spec, since the current version is landed and on its way to CR.  Personally I like the `Readable/WritableStreams` (see e.g. this [proposal](https://discourse.wicg.io/t/rfc-proposal-for-integration-streams-mediastreamtrack-api/2256))

**Comment by alvestrand** [comment]
The recording spec is heavily used, so removing the existing blob-based API is not realistic in the short run. So I've labelled this "enhancement" and will treat it as a request for additional API surface.

**Comment by youennf** [comment]
Sorry for not having seen #87 before.
Let's close it as a dupe of #87.
