### ISSUE TITLE
BlobEvent is defined in both MediaStream Recorder and MediaStream ImageCapture, consider factoring them out

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#16]
In [1] and [2], respectively.

[1] http://www.w3.org/TR/mediastream-recording/#blob-event
[2] http://www.w3.org/TR/image-capture/#blobevent

**Comment by alvestrand** [comment]
If we don't use BlobEvent (see #17), this is moot.

**Comment by yell0wd0g** [comment]
`BlobEvent` has been removed from the Image Capture spec in favour of Promises, so closing this issue.
