### ISSUE TITLE
MediaStream does not expose a RecordingState

### ISSUE THREAD

**Issue by chrisguttandin** [w3c/mediacapture-record#181]
I think I found a misplaced reference in the [algorithm which describes the start() method](https://w3c.github.io/mediacapture-record/#dom-mediarecorder-start).

Bullet point 7 says: "If stream is inactive, throw a NotSupportedError DOMException and abort these steps." The word ["inactive"](https://w3c.github.io/mediacapture-record/#dom-recordingstate-inactive) is a link to the definition of the RecordingState enum. Was this possibly meant to reference the ["active" attribute of a MediaStream](https://www.w3.org/TR/mediacapture-streams/#dom-mediastream-active) instead?

**Comment by Pehrsons** [comment]
Yes, this should reference [`inactive`](https://www.w3.org/TR/mediacapture-streams/#stream-inactive) in mediacapture-streams.

**Comment by chrisguttandin** [comment]
Thank you, @Pehrsons.

I would have sent a PR myself but I had no idea how to change the link with Bikeshed.

**Comment by chrisguttandin** [comment]
I think this can be closed now since #184 is merged.

@Pehrsons: Should I close the issue because I opened it? Or should it be done by one of the editors?

**Comment by Pehrsons** [comment]
This can be closed, yes. I don't have the button to do it so you go ahead. For some reason it didn't happen automatically when #184 was merged.
