### ISSUE TITLE
Is there any implementer objection to supporting audio/wav mimeType?

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-record#198]
`"audio/wav"` `mimeType` would be useful. The topic arises not infrequently, e.g.,

- https://stackoverflow.com/questions/51399121/how-to-save-int16array-buffer-to-wav-file-node-js

as to how to encode audio as WAV file, and conversely, how to decode WAV or PCM without WAV header to `Float32Array`

- https://github.com/WebAudio/web-audio-api-v2/issues/63 

Before file bugs at browsers requesting support for `audio/wav` `mimeType` is there any implementer objection to supporting `audio/wav` `mimeType`?

**Comment by guest271314** [comment]
Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1379241
Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1070108

**Comment by dontcallmedom** [comment]
the specification doesn't mandate any mime type supports, so this is an implementation-dependant choice and thus implementation-only relevant.
