### ISSUE TITLE
 DOMError is not an event? 

### ISSUE THREAD

**Issue by perkj** [w3c/mediacapture-record#2]
http://w3c.github.io/mediacapture-record/MediaRecorder.html#error-handling

Also - according to 
http://www.w3.org/TR/dom/#interface-domerror  - DOMError is going away. 

Should this really be a new event , similar to BlobEvent  that have a name and a message but the name must be a from the the error enums. 

enum RecordingErrorNameEnum {
    "InvalidState",
    "OutOfMemory",
    "IllegalStreamModification",
    "SecurityError",
    "OtherRecordingError"
};

[
    NoInterfaceObject
]
interface MediaRecorderErrorEvent : Event {
  readonly attribute RecordingErrorNameEnum name;
  readonly attribute DOMString message;
};

Alternatively - do as http://www.w3.org/TR/FileAPI/#FileReader-interface
- have a DOMError attribute and a simple onerror event.

**Comment by alvestrand** [comment]
This document should be following the same pattern as Media Capture and Streams for its errors.

**Comment by ghost** [comment]
Yes, that's probably right.  In the past there was discussion about 
whether our errors should be based on DOMError, but if it's going away 
that's no longer an issue.  There was also discussion about whether to 
re-use MediaStreamError, but the error is not necessarily with the 
MediaStream, so it makes sense to have a different class.
- Jim

**Comment by ghost** [comment]
DOMError has been removed from the draft.
