### ISSUE TITLE
MediaRecorder : frame loss on mobile devices 

### ISSUE THREAD

**Issue by sr1dh4r** [w3c/mediacapture-record#201]
**Browser name including version (e.g. Chrome 64.0.3282.119)**

Chrome 83.0.4103.106

**Description**
Frames are lost in the recording.

**Steps to reproduce**
Testing:

Open https://webrtc.github.io/samples/src/content/getusermedia/record/ link in mobile chrome browser on android.

**Expected results**
Recording should be available without any frame drop.

**Actual results**
Recording has a lot of frame loss.

**Related issues**
https://github.com/w3c/mediacapture-record/issues/177
https://github.com/webrtc/samples/issues/1331 (Opening it here since it seems more relevant)

**Comment by guest271314** [comment]
How is frame loss determined?

Have you tried using `start(0)` with `requetData()` and comparing result with `start()` without `timeSlice`?

Have you tested with `h264`/`avc1` codec?

**Comment by sr1dh4r** [comment]
> How is frame loss determined?
Visually, please try the linked shared on a mobile device.
> 
> Have you tried using `start(0)` with `requetData()` and comparing result with `start()` without `timeSlice`?
Yes, I see no difference.
> 
> Have you tested with `h264`/`avc1` codec?
I have tested against vp8, vp9 webm codecs as described in #177 and I don't expect it to be any different.

**Comment by guest271314** [comment]
What are the steps to reproduce?

"a mobile device" is a broad category. What specific device?

How did you verify frame loss other than visually?

What is the expected result?

**Comment by sr1dh4r** [comment]
> What are the steps to reproduce?
> 
> "a mobile device" is a broad category. What specific device?
> 
> How did you verify frame loss other than visually?
> 
> What is the expected result?

https://github.com/w3c/mediacapture-record/issues/201#issue-655367621

**Comment by dontcallmedom** [comment]
unless there are clear reasons why the design of the spec makes it not usable on mobile devices (which this issue doesn't cover), this sounds like an implementation issue. Closing until further motivation is given
