### ISSUE TITLE
Use non-abbreviated terms in bitrates

### ISSUE THREAD

**Issue by cynthia** [w3c/mediacapture-record#203]
In https://github.com/w3ctag/design-reviews/issues/540, we suggested that non-abbreviated forms for the bitrate enum would be better for user ergonomics; but it looks like that change has not been made yet.

Roughly this:
s/vbr/variable/
s/cbr/constant/

This issue is to track that suggestion.

**Comment by dontcallmedom** [comment]
this was done in #210, closing
