### ISSUE TITLE
Edge cases related to firing start and stop events

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-record#204]
Chrome and Firefox do not seem to agree on edge cases related to firing start and stop events when synchronous calls are made. See for instance https://jsfiddle.net/ukqwrvL3/ or https://jsfiddle.net/1kxtpefw/.
From my reading of the spec, it seems that on both fiddle, the start event should be fired, even if the recorder was stopped.

**Comment by youennf** [comment]
Uploaded WPT tests that align with my understanding of the spec at https://github.com/web-platform-tests/wpt/pull/26006/files.

**Comment by Pehrsons** [comment]
> Uploaded WPT tests that align with my understanding of the spec at https://github.com/web-platform-tests/wpt/pull/26006/files.

These match my understanding of the spec too.

**Comment by Pehrsons** [comment]
On https://bugs.webkit.org/attachment.cgi?id=410620&action=diff#a/LayoutTests/imported/w3c/web-platform-tests/mediacapture-record/MediaRecorder-stop-expected.txt_sec1:
NB that WPT MediaRecorder-stop.html is wrong regarding throwing in `stop()`.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1669444, where I intend to fix this.

**Comment by youennf** [comment]
> See https://bugzilla.mozilla.org/show_bug.cgi?id=1669444, where I intend to fix this.

Tackling this in https://bugs.webkit.org/show_bug.cgi?id=217705.
WPT PR is at https://github.com/web-platform-tests/wpt/pull/26114

**Comment by dontcallmedom** [comment]
since webkit and gecko agrees on a common interpretation of the spec, is any spec work needed here?
