### ISSUE TITLE
Consider using Uint8Array instead of Blob for recorded data Event

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#21]
MediaStream Recording API sends recorded data to JS as a Blob wrapped into an Event. Consider using Uint8Array instead of the Blob, to speed up processing.

**Comment by yell0wd0g** [comment]
Also, this would allow recording and sending directly into a MediaSource's SourceBuffer, which has a method appendBuffer() [1] that would happily receive a TypedArray (a Uint8Array in this case).

[1] https://w3c.github.io/media-source/#widl-SourceBuffer-appendBuffer-void-ArrayBuffer-data

**Comment by yell0wd0g** [comment]
Reading @martinthomson comment in https://github.com/domenic/streaming-mediastreams/issues/5 :

> I believe that the main reason for using a blob is that the data is not in-memory. It might be in a buffer in the graphics subsystem somewhere.

I think this applies to the present case, so I'll preventively add a note in the doc and close this issue. Please raise your voices if in disagreement.

**Comment by yell0wd0g** [comment]
@martinthomson, does your comment still apply and apply to MediaRecorder? In that case, should we close this issue?

**Comment by martinthomson** [comment]
Yes, I think that it applies.  A blob can be converted to an ArrayBuffer as needed, where the performance cost is accepted.  Converting by default will be expensive.

**Comment by yell0wd0g** [comment]
Closing per @martinthomson comment.
