### ISSUE TITLE
MediaRecorderErrorEvent is a bad idea; use ErrorEvent instead

### ISSUE THREAD

**Issue by domenic** [w3c/mediacapture-record#211]
[ErrorEvent](https://html.spec.whatwg.org/#errorevent) already exists and serves this purpose fine. We shouldn't propagate multiple such types on the web platform.

**Comment by alvestrand** [comment]
MDN claims that Firefox and Safari implement MediaRecorderErrorEvent (https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorderErrorEvent#methods)

WPT.FYI seems to indicate that only Firefox does:  https://wpt.fyi/results/mediacapture-record/idlharness.window.html?label=experimental&label=master&aligned

**Comment by domenic** [comment]
Oh, thanks, I thought it was nobody else since the blink-dev Intent to Prototype indicated no signals from other browsers...

I think this would likely be a backward-compatible change for Firefox since `event.error` would still exist and return the same value. The only thing that would break is if someone is doing `new MediaRecorderErrorEvent(...)` which seems pretty unlikely.

**Comment by dontcallmedom** [comment]
looking [on github](https://github.com/search?l=JavaScript&p=11&q=%22new+MediaRecorderErrorEvent%22&type=Code) and [on searchcode](https://searchcode.com/?q=%22new+MediaRecorderErrorEvent%22&lan=22), the only occurrences of `new MediaRecorderErrorEvent()` seems to be in WPT.

I've filed https://github.com/w3c/mediacapture-record/pull/212 for a spec change, and drafted https://github.com/web-platform-tests/wpt/pull/32380 for the associated WPT changes.

**Comment by foolip** [comment]
I've done a search for "MediaRecorderErrorEvent." (trailing dot) in httparchive and there were only 4 matches. All 4 of those look like generated stuff from IDL or some other API listing. https://documents.devdocs.io/dom/index.json?1634928100 is one example, which I think is a mapping of features to MDN pages.
