### ISSUE TITLE
Navigator.mediadevices.getUserMedia api is not working iOS Chrome

### ISSUE THREAD

**Issue by SwathiMethuku** [w3c/mediacapture-record#214]
navigator.mediaDevices.getUserMedia({ video: true, audio: true}).then());

console log in ipad(IOS 13.3.2) chrome(
ERROR: TypeError: undefined is not an object(evaluating 'navigator.mediaDevices.getUserMedia')

**Comment by fippo** [comment]
This is not a spec issue so doesn't belong here. See [here](https://bugs.chromium.org/p/chromium/issues/detail?id=752458) for when Chrome/ios shipped but in general advice to check for support (i.e. that navigator.mediaDevices and navigator.mediaDevices.getUserMedia) both exist before trying to call them.
