### ISSUE TITLE
What to do both videoKeyFrameIntervalDuration and videoKeyFrameIntervalCount are specified?

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-record#219]
The https://github.com/w3c/mediacapture-record/pull/216/files PR is a bit vague here saying the UA may ignore either, we may want to say what to do at avoid interop issues

**Comment by foolip** [comment]
What does Chromium's implementation do?

**Comment by foolip** [comment]
@youennf had a concrete suggestion in https://github.com/w3c/mediacapture-record/pull/216#discussion_r1158798161 (disallow combining the two) that seems simple to understand at least.

**Comment by youennf** [comment]
It seems @handellm plans to write WPT tests for this new API.
Let's resolve this issue at the same time we add the tests and before the implementations ship.
@handellm, @Pehrsons any preference on either throwing or ignoring one or the other?

**Comment by Pehrsons** [comment]
I have no experience trying to use both so being defensive and throwing for now sounds good to me.

**Comment by handellm** [comment]
Throwing SGTM
