### ISSUE TITLE
"raise a MediaRecorderErrorEvent" should fire an event?

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#22]
http://w3c.github.io/mediacapture-record/MediaRecorder.html#error-handling

This does not say what the name of the event is ("error" in Blink) or what the event target is.

See https://xhr.spec.whatwg.org/#concept-event-fire-progress for an example of how to phrase this.

(The section also talks about error callbacks, where it means error events I think.)

**Comment by yell0wd0g** [comment]
Should be closed, please double check. Reopen if in doubt.

**Comment by foolip** [comment]
http://w3c.github.io/mediacapture-record/MediaRecorder.html#error-handling still has MediaRecorderErrorEvent, should the published version really be that far behind master? (Many specs keep them always in sync, simply keeping unfinished things off of master.)

**Comment by yell0wd0g** [comment]
@foolip Just did another release cycle (see http://w3c.github.io/mediacapture-record/MediaRecorder.html), issue being that the `release.sh` script is very manual and tends to get stuck in rebases of `gh-pages` versus `master` which makes me feel very lazy about using it :-)
