### ISSUE TITLE
Consider renaming attribute |mimeType|

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#35]
This is taken off from https://github.com/w3c/mediacapture-record/issues/10:

> If there isn't already content that depends on it, it would also be nice to rename MediaRecorder.mimeType.

Since this attribute is already implemented in both Gecko [1] and Blink [2], this might be less than straightforward.

[1] https://github.com/mozilla/gecko-dev/blob/master/dom/webidl/MediaRecorder.webidl#L24
[2] https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/mediarecorder/MediaRecorder.idl&q=mediarecorder.idl%20mimetype&sq=package:chromium&type=cs&l=20

**Comment by foolip** [comment]
CC @randylin and @rocallahan, who added and reviewed this in Gecko in https://github.com/mozilla/gecko-dev/commit/9175f35127a3f9c85a72f58c16fc8eb015bce953

**Comment by rocallahan** [comment]
If anything `mimeType` is a better name than `type` (more descriptive yet still not long) so there's just a consistency argument AFAICT, and I think a weak one. I really don't think this is worth changing.

**Comment by foolip** [comment]
These are the various media-related APIs that deal with MIME types that I know of:
- `canPlayType` on [`HTMLMediaElement`](https://html.spec.whatwg.org/#media-elements)
- `type` on [`HTMLSourceElement`](https://html.spec.whatwg.org/#the-source-element)
- `isTypeSupported` on [`MediaSource`](http://w3c.github.io/media-source/#mediasource) (and now `MediaRecorder`)
- `contentType` on [`MediaKeySystemMediaCapability`](https://w3c.github.io/encrypted-media/#mediakeysystemmediacapability-dictionary)

`mimeType` completes the set of possible names for this concept, I think :)

If nobody working on Gecko would like to change this, then there is nothing to do here.

**Comment by foolip** [comment]
@miguelao, can you close this so that the status is clear?
