### ISSUE TITLE
MediaRecorderOptions' mimeType need not have a default value

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#40]
http://w3c.github.io/mediacapture-record/MediaRecorder.html#MediaRecorderOptions

Defaulting to the empty string is not necessary, and also means that passing `{}` should be equivalent to `{ mimeType: "" }`, but that should throw an exception since the empty string is not a valid mime type. (I assume that an exception is thrown for any input where `isTypeSupported` would return false.)

**Comment by yell0wd0g** [comment]
Actually on that, I was considering an imbalance: isTypeSupported("") should return false in the current spec, whereas a constructor call to MediaRecorder() with an empty mimeType, basically it should instruct the UA to use whichever container and codecs it deems preferred, right? (I'm thinking about potential JS developers that don't care about the MR internals as long as the recorded result is "playable"...)

Does this make sense? If so, then we should amend the spec in those terms.

**Comment by foolip** [comment]
Since the options dictionary is optional, omitting the mimeType must do something, and I assume that means that the UA should pick its default container and codecs. To have another way of achieving the same thing doesn't seem necessary. To pick a random dictionary with a DOMString with no default value, there's [`RequestInit`](https://fetch.spec.whatwg.org/#requestinit) in Fetch.

(Note that `{ mimeType: undefined }` should per Web IDL treat mimeType as missing, if you're worried about passing along arguments from elsewhere, like `{ mimeType: elsewhere.mimeType }`. That works in Firefox, but not in Chromium. If this is the core of the concern, I can try to find the bindings bug for that.)

**Comment by yell0wd0g** [comment]
@foolip, I think this is solved per #45, please check and close issue if satisfied.

**Comment by foolip** [comment]
The spec now says "If type is an empty string, then return true (note that this case is essentially equivalent to leaving up to the UA the choice of container and codecs on constructor)" which doesn't seem right.

In order to get the default container and codec, you should not specify the `mimeType` dictionary member at all, and `new MediaRecorder(stream, { mimeType: "" })` should throw `NotSupportedError`, IMHO.

**Comment by foolip** [comment]
(And sorry for the slow feedback, I'm still working through the holiday backlog.)

**Comment by foolip** [comment]
Another way to see that this is strange is to consider the difference between `new MediaRecorder(stream).mimeType` and  `new MediaRecorder(stream, { mimeType: "" }).mimeType`. If both constructors do the same thing, then the `mimeType` attribute should be the same, but the spec says "The container format, whether passed in to the constructor or defaulted, will be used as the value of the `mimeType` attribute" with no special case for the empty string.

**Comment by yell0wd0g** [comment]
`mimeType` has no default in the master head, @foolip I'm closing this issue then, please reopen if still not groking, cheers!

**Comment by foolip** [comment]
Confirmed: http://w3c.github.io/mediacapture-record/MediaRecorder.html#idl-def-MediaRecorderOptions
