### ISSUE TITLE
Consider merging ErrorEvent definition with Media Capture and Streams

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#42]
@beverloo insightfully commented in https://github.com/w3c/mediacapture-record/issues/31#issuecomment-166599507 

> https://html.spec.whatwg.org/multipage/webappapis.html#the-errorevent-interface
> http://w3c.github.io/mediacapture-main/#errorevent (duplicated [here](https://rawgit.com/w3c/mediacapture-record/master/MediaRecorder.html#errorevent) — could we introduce a dependency instead?)
> 
> This seems unfortunate. The media one is a subset of the HTML one, compatible due to the nature of any error in both the interface and the init dictionary.

**Comment by yell0wd0g** [comment]
Also filed as https://github.com/w3c/mediacapture-main/issues/298 so both repos have it.

**Comment by jan-ivar** [comment]
See https://github.com/w3c/mediacapture-main/issues/335

**Comment by yell0wd0g** [comment]
Closing this one since w3c/mediacapture-main#298 and w3c/mediacapture-main#335 are closed and there seems to be consensus that [`ErrorEvent`](https://html.spec.whatwg.org/multipage/webappapis.html#the-errorevent-interface), with its `filename`, `lineno` and `colno` is not useful in the current context.
