### ISSUE TITLE
Provide Surface API for reading back the configured encoding bitrate(s)

### ISSUE THREAD

**Issue by yell0wd0g** [w3c/mediacapture-record#43]
Section [MediaRecorder Properties](https://rawgit.com/w3c/mediacapture-record/master/MediaRecorder.html#properties) says:

> [TO DO: Provide API surface to set and read these. When that is done, this section will be removed.]

this is the issue for that TODO, for the bitrate options concretely.

(It's basically a follow up of @mreavy "improve bitrate control in MediaRecorder" #20 - discussed with @tdaede).

**Comment by mreavy** [comment]
That looks good, except that the three bitrate properties should all use the same or similar language to say that the target bitrate isn't guaranteed.  I'll close #20

**Comment by yell0wd0g** [comment]
@mreavy, re. your comment, from https://rawgit.com/w3c/mediacapture-record/master/MediaRecorder.html#dictionary-mediarecorderoptions-members, 
- `audioBitsPerSecond`:  `This is a hint for the encoder and the value might only be achieved over a long time.`
- `videoBitsPerSecond` : `This is a hint for the encoder and the value might be surpassed or not achieved.`
- `bitsPerSecond`: `This parameter is a hint for the encoder(s) and the total value might be surpassed or not achieved at all.`

**Comment by mreavy** [comment]
@miguelao :I'm sorry, I don't see a question here - those are the descriptions that need to be synchronized, yes.

**Comment by yell0wd0g** [comment]
Oh I see, you meant that the three should say a similar thing, gotcha.

**Comment by yell0wd0g** [comment]
Closed as per #47
