### ISSUE TITLE
MediaRecorder needs more clarity for handling multiple audio and video tracks

### ISSUE THREAD

**Issue by ghost** [w3c/mediacapture-record#5]
Giji Gangadharan 2014-08-13 12:10:28 UTC

There is no clarity in using mimetype for a MediaStream having multiple audio and video tracks. 
In case of multiple video tracks, all will get encoded in same format. There is no explanation to record different tracks in different format.

Comment 1 Harald Alvestrand 2014-08-13 12:27:22 UTC

Normally the mediatype (MIME type) would indicate the container format, and whatever parameters the container format uses to indicate which codecs the file contains.

For instance, the .webm file extension, with MIME type video/webm, is normally using the OGG Vorbis audio codec and the VP8 video codec.

The spec needs to be clear that the MIME type is the container's MIME type; that may be obvious to some, but not to all.

Comment 2 Giji Gangadharan 2014-08-21 14:05:48 UTC

Consider a case where a MediaStream has multiple video tracks (MediaStreamTrack). Here, the same container format (MIME Type) will be used for recording all the tracks?

**Comment by yell0wd0g** [comment]
This is an old Issue, now [we can read](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-mimetype):
> The MIME type [RFC2046] that has been selected as the container for recording. This entry includes all the parameters to the base mimeType.

So I think it's clear.
