### ISSUE TITLE
Async algorithms .start(), .stop(). pause() et al. need major work

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-record#54]
The fundamental design of async algorithms should be:
1. You do some stuff synchronously up front to make sure the API call makes sense, and throw if not.
2. You return.
3. You do async stuff like waiting, fetching, etc. [_in parallel_](https://html.spec.whatwg.org/#in-parallel).
4. Any further communication with your original caller happens from tasks you post to a task source.

Compare this to the `.start()` algorithm (and most of the others):
1. Queues a task immediately on the _DOM manipulation task source_ (effectively the main thread!).
2. It never returns.
3. It throws exceptions from a queued task, which never make it back to content.
4. It blocks the main thread with language like "wait until media becomes available".
5. It fires events like `stop` synchronously from code that seems asynchronous, causing JS concurrency.

I suspect all the algorithms that queue to _DOM manipulation task source_ and then wait should be rewritten this way. Some like `.resume()` may be fine as-is, though I'm curious why we seem to prefer changing state on the next event loop rather than synchronously?

**Comment by yell0wd0g** [comment]
@jan-ivar, with #56 and the rewriting in #83, what's still needed for this issue to be addressed?

**Comment by jan-ivar** [comment]
@miguelao These still need to be addressed for all methods other than _start_. See my review comments in https://github.com/w3c/mediacapture-record/pull/83 for details.

**Comment by yell0wd0g** [comment]
Rewrote the algorithms so they read more like the following pseudocode:
- `the UA must run the following steps`:
- something is wrong upfront: `throw an` bla `DOMException, else`queue a task, using the DOM manipulation task source, that runs the following steps:`
  - do stuff
  - something goes wrong: `fire an event` named whatever, etc.

is this closer to what you meant?

**Comment by yell0wd0g** [comment]
@jan-ivar could you please have another look at the current `HEAD`? We can clean it up, if needed, from there.

**Comment by jan-ivar** [comment]
Done. lgtm. comments in https://github.com/w3c/mediacapture-record/issues/83

**Comment by yell0wd0g** [comment]
Please take another look at the current status, thanks!

**Comment by jan-ivar** [comment]
lgtm.

**Comment by yell0wd0g** [comment]
Closing per https://github.com/w3c/mediacapture-record/issues/54#issuecomment-258252176
