### ISSUE TITLE
Can .start() throw a SecurityError?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-record#55]
The following text is quite troubling it if doesn't (emphasis mine):

> "If at any point the stream's isolation properties change so that MediaRecorder is no longer allowed access to it, the UA must stop recording, discard any data that it has gathered and throw a SecurityError DOMException followed by the stop event. If the UA is unable to start recording or at any point is unable to continue recording **_(i.e., for reasons other than a security violation)**_, it must throw an UnknownError DOMException, followed by a dataavailable event containing the Blob it has gathered, follwed by the stop event."

(Nevermind that it's impossible to "throw a SecurityError" for runtime errors, I think it means fire the `error` event.)

If `.start()` doesn't throw `SecurityError` then this is a hole big enough to drive an already isolated stream through (since a stream doesn't really "change" if it starts out, and stays, isolated).

**Comment by jan-ivar** [comment]
Unfortunately, the algorithm for `.start` has no mention of throwing `SecurityError`.

**Comment by jan-ivar** [comment]
There's two ways to solve this.

This came up because Firefox recently changed its behavior: `.start` used to throw `SecurityError`, but due to a code reorganization, it now fires the `error` event instead. Almost the same effect, just one fewer code-path to handle. I was told there wasn't any technical necessity behind the change, so we could go either way.

**Comment by martinthomson** [comment]
In the interest of making errors available in the context in which they can be most readily acted upon, I think that firing `SecurityError` from `start()` makes the most sense to me.

**Comment by jan-ivar** [comment]
@martinthomson good principle. I buy it.

**Comment by yell0wd0g** [comment]
@jan-ivar can you take a look at #83 wording (or the status of the document after this PR lands) and see if sth/what needs to be done? Thx!

**Comment by jan-ivar** [comment]
@miguelao This particular issue was already addressed by https://github.com/w3c/mediacapture-record/pull/61 so we should be good here.
