### ISSUE TITLE
MediaRecorder should be able to encode an AudioBuffer

### ISSUE THREAD

**Issue by AshleyScirra** [w3c/mediacapture-record#6]
MediaRecorder currently only consumes a MediaStream, which can only run in real-time. For some use-cases, this is a significant limitation. Encoding as fast as possible is important for use cases like:
- a tool to encode or transcode audio files
- a multi-track audio recorder (DAW) that needs to "bounce" (export a mix-down) to a compressed format
- compressing the result of OfflineAudioContext, which renders an AudioBuffer (and cannot be routed to a MediaStream unless it is subsequently played back at real-time speed).

Any of these cases are possible by routing an AudioBuffer to a MediaStreamAudioDestinationNode, but it must run in real-time. To encode e.g. a 30-minute long track, this is prohibitively long and could be done in a few seconds on a powerful CPU.

I think the easiest way to support this is to allow a MediaStream _or_ an AudioBuffer to be passed to the MediaRecorder constructor. If an AudioBuffer is passed, then the MediaRecorder start() method will simply run as fast as possible through the buffer.

**Comment by yell0wd0g** [comment]
@AshleyScirra , although I sympathise with the proposal, I'm not sure this is the best Spec to file it since, as you correctly say, `MediaRecorder currently only consumes a MediaStream, which can only run in real-time.`. I'd say the best bet is to have a recording API to WebAudio (https://github.com/WebAudio/web-audio-api). I'm preventively closing this Issue please refer to it from the WebAudio sister Issue and cheers!

**Comment by mhofman** [comment]
I believe this is something that needs to be tackled at the Web Platform level. There are other places where the separation between "real-time", "playback" and "offline" media prevents some things from being done easily:
https://github.com/w3c/mediacapture-fromelement/issues/19
https://github.com/w3c/mediacapture-worker/issues/33

**Comment by AshleyScirra** [comment]
@miguelao - it sounds like you're referring to an existing WebAudio issue, but I'm not sure which one, can you link me to that? Or did you intend for me to file a new issue there?

I am very skeptical that recording features should be added anywhere else. For a clear and consistent platform, I think there should be one spec for one feature. Fragmenting media recording across different APIs with different specs seems very likely to end up reinventing the wheel and causes confusion for web developers since there is no longer a clear answer to the question "how do I record media?". Is there any particular reason MediaRecorder can't be extended in the manner I suggested? Have implementers commented saying that it is infeasible for example?

**Comment by mhofman** [comment]
Regarding your proposal, I don't think an AudioBuffer is the right approach.
1) It only solves the audio use case.
2) It requires the samples for the whole length to be kept in memory, i.e. you cannot do any progressive processing.

Something based on Streams would be a better abstraction, unfortunately Streams and anything media is not yet integrated in the Web Platform.

**Comment by AshleyScirra** [comment]
OK, I accept that. But then isn't the solution to allow MediaRecorder to take a ReadableStream? Shouldn't such an issue be opened on this spec?

**Comment by yell0wd0g** [comment]
@mhofman, I coincide, and have used myself often, the taxonomy of real-time versus, well, non-real-time as the only possible distinction between `MediaStream` "things" and "the others", but honestly there should not be such distinction at the Web Platform level, right?

**Comment by yell0wd0g** [comment]
@domenic took time to explore this possibility in a separate MediaRecorder-from-ReadableStream that might be relevant for the discussion at hand:  https://domenic.github.io/streaming-mediastreams/.
