### ISSUE TITLE
To "dispatch" and "fire" events should reference DOM concepts

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#69]
Context: https://github.com/w3c/mediacapture-record/pull/56#discussion_r60556409

To fire plain/simple events, use DOM's [fire an event named _e_](https://dom.spec.whatwg.org/#concept-event-fire), example in https://xhr.spec.whatwg.org/ if you search for "Fire an event named readystatechange".

To fire other kinds of events, https://w3c.github.io/mediacapture-record/MediaRecorder.html#dfn-firing-an-error-event-named-e looks good, but "dispatched" should link to https://dom.spec.whatwg.org/#concept-event-dispatch

(There's already a https://www.w3.org/TR/dom/ reference and this issue is not about whether to use the WHATWG or the W3C spec.)

**Comment by yell0wd0g** [comment]
@foolip, rewritten to use `fire an event named Bla`, and added link to the appropriate [`dispatched`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#errorevent) reference. Closing this issue preventively after #81, please have a look.

**Comment by foolip** [comment]
Followed up in https://github.com/w3c/mediacapture-record/pull/81#pullrequestreview-6518385
