### ISSUE TITLE
[TreatUndefinedAs=Missing] is gone from Web IDL

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#7]
http://w3c.github.io/mediacapture-record/MediaRecorder.html#MediaRecorderAPI

http://heycam.github.io/webidl/ says "Removed [TreatUndefinedAs]."

**Comment by yell0wd0g** [comment]
Should be closed now.

**Comment by foolip** [comment]
It looks like http://w3c.github.io/mediacapture-record/MediaRecorder.html isn't automatically updated, but I can confirm that it's fixed in the repo.

**Comment by yell0wd0g** [comment]
I wanted to bundle a few changes before releasing to w3c.github.io (I understand is not automatic), in the meantime http://rawgit.com/w3c/mediacapture-record/master/MediaRecorder.html should reflect the latest changes.
