### ISSUE TITLE
WG CR review for mediacapture-record

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-record#72]
This issue serves to track internal WG review (in the WGs making up the mediacapture TF) of the mediacapture-record document for CR publication.
If you have reviewed the document, please add a “thumbs up” reaction to the issue.
If you find issues that you think need addressing before CR publication, please file the issue in Github and mention it in the comments.

The review lasts until Thursday, October 12, 2016. At that time, the chairs will decide whether or not the review result warrants asking the wider community to review the document for CR; if we do ask the wider community, a similar issue wil be filed for tracking that review.

**Comment by fluffy** [comment]
There are bugs that are almost 2 years old and still need to be resolved before this goes to CR. I do not think this needs many of the existing issues resolved before it is even ready for review to decide if it is ready to go to CR.
