### ISSUE TITLE
Support for timecodes

### ISSUE THREAD

**Issue by sole** [w3c/mediacapture-record#73]
An "Anonymous Developer" asked me for a way to insert [timecodes](https://en.wikipedia.org/wiki/Timecode) in the captured streams. They also asked for the counterpart: being able to read timecodes from streams (be it getUserMedia originated streams, or new streams created with MediaCapture, etc).

This would allow for video editing software to be built right in the browser, as timecodes allow for better accuracy for frame seeking than `getCurrentTime()`.

Apologies in advance, but I'm not quite sure if this should be filed here or somewhere else where media streams are defined.

**Comment by yell0wd0g** [comment]
Note that this information is part of the container per-frame headers that are inside the `data` field. This information is, however, hard to get to -- essentially it means demultiplexing quite some parts of the output.

That said, we could have a [`DOMTimeStamp`](https://www.w3.org/TR/WebIDL/#common-DOMTimeStamp) field in the [`BlobEvent`](file:///Users/mcasas/p/github/mediacapture-record/MediaRecorder.html#blob-event):

```
interface BlobEvent : Event {
  //...
  readonly attribute DOMTimeStamp timeStamp;
};
```

The `timeStamp` would not necessarily refer to the inner `data` but to the `Event` itself (i.e. if `data` was a chunk encoded+multiplexed video frames and audio buffers, `timeStamp` would refer to the first one). WDYT, @foolip, @fluffy ?

**Comment by foolip** [comment]
Something like that might work, but note that Event already has a timeStamp attribute, so it'd have to be some other name. I also guess it'd be a point on a timeline and not really a date-and-time?

**Comment by yell0wd0g** [comment]
Then maybe just reuse the original terminology:

```
interface BlobEvent : Event {
  //...
  readonly attribute DOMTimeStamp timecode;
};
```

Also, note that `DOMTimestamp`is defined as:

> The DOMTimeStamp type is used for representing a number of milliseconds, either as an absolute time (relative to some epoch) or as a relative amount of time. Specifications that use this type will need to define how the number of milliseconds is to be interpreted.

which I interpret essentially as a large integer detailing milliseconds and not necessarily a time from some epoch.

**Comment by foolip** [comment]
Uh, right, it's on the same timeline as `performance.now()`, not a date-time.

**Comment by yell0wd0g** [comment]
@sole step 1 done.  Now for the implementations.
