### ISSUE TITLE
Like to use promise to return recorded data 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-record#75]

**Comment by yell0wd0g** [comment]
How would you structure this alternative vs the current event-based?

E.g.. would you envision the method `start()` to be formulated as,
`Promise<DataReader> start(optional params);`
where

```
interface DataReader {
  ondataavailable; 
  onstart;
  onstop;
  onerror;
  // ... etc
};
```

Or would you use the Promise to read each individual chunk of data, i.e.
`Promise<Blob> readChunkOfData();`

**Comment by yell0wd0g** [comment]
ping @fluffy

**Comment by dontcallmedom** [comment]
closing with the reasoning documented in https://github.com/w3c/mediacapture-record/issues/137#issuecomment-854412575
