### ISSUE TITLE
Unclear on mine type paramters

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-record#76]
It has the text 

> The container and codec format(s) for the recording, which may include any parameters that are defined for the format.

Not sure what types of parameters are included here. Can I provide H.264 fmtp like parameters?

**Comment by yell0wd0g** [comment]
Mimes are weird creatures, specially in what regards to the parameters (i.e. those entries after the type and subtype): they are subtype (==codec) specific, in other words you should go to the [IANA Media Types](http://www.iana.org/assignments/media-types/media-types.xhtml#video) appropriate entry and check the specifics. The Spec delegates the definition of any `parameters` to the appropriate MIME type template.  For H264 for example I see there is a parameter 'use-level-src-parameter-sets' that might be what you are referring to. Does this make sense?

**Comment by yell0wd0g** [comment]
More conversation in #78, @fluffy, let's have any further conversation there.
