### ISSUE TITLE
Incorrect use of mime type 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-record#78]
The draft calls things that are more than a mime type a mine type. This should be correct and it should reference rfc6381.  Right now were it claims to take a mime type, it can probably only really take a container mine type with possible parameters that specify the mine types for the codecs used by the container.

**Comment by yell0wd0g** [comment]
Also touched by #83.

**Comment by yell0wd0g** [comment]
@fluffy can you take a look at the wording in https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-mimetype and https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorderoptions-mimetype and see if they address your concerns? Thx

**Comment by yell0wd0g** [comment]
ping @fluffy.

**Comment by yell0wd0g** [comment]
reping @fluffy.  Closing this issue preventively, please reopen if not satisfied.
