### ISSUE TITLE
Clarify ```ignoreMutedMedia```

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-record#79]
`ignoreMutedMedia` talks about a muted _MediaStream_, however, a MediaStream can't be muted, so perhaps it should say _MediaStreamTrack_?

Further, the last sentence speccing the `start` methods says that muted tracks will be recorded as silence/blackness, but should not `ignoreMutedMedia` make a difference?

**Comment by yell0wd0g** [comment]
@stefhak please take a look and close this bug if satisfied, cheers!

**Comment by stefhak** [comment]
LGTM! Closing.
