### ISSUE TITLE
"Enum" as part of enum name "RecordingStateEnum" is unusual

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#8]
Simply calling the enum "RecordingState" would be more idiomatic. This is entirely editoral.

**Comment by foolip** [comment]
There's also `RecordingErrorNameEnum`

**Comment by yell0wd0g** [comment]
Plz close this issue if https://github.com/w3c/mediacapture-record/pull/28 is enough.

**Comment by foolip** [comment]
:+1:
