### ISSUE TITLE
Add explainer document

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-record#86]
From [TAG review](https://github.com/w3ctag/spec-reviews/issues/131#issuecomment-257478126):
> Would like to see an explainer collating the scenarios, how to use them, and example code for each

**Comment by yell0wd0g** [comment]
I added a small [examples section](https://w3c.github.io/mediacapture-record/MediaRecorder.html#examples) (with live counterparts). 

Would that be enough @travisleithead or how can I beef them up?

Re. "explainer": I understand that, in the context of, e.g. a WICG spec, such an addendum might be interesting and desirable, however, in a Spec heading for CR status, is it still relevant to centralize in a(n extra) non-normative document the reasons why the former is interesting and/or relevant? What is to be found in that document that shouldn't be in a non-normative section of the Spec?

**Comment by alvestrand** [comment]
An "explainer" might be a section in the spec too. I think "intro" and "examples" sections cover the same need.

**Comment by travisleithead** [comment]
Thanks for doing this! Appreciate the example. Feel free to close this feedback at your leisure.
