### ISSUE TITLE
isTypeSupported() algorithm should be more specific

### ISSUE THREAD

**Issue by ddorwin** [w3c/mediacapture-record#92]
The [isTypeSupported() algorithm](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-istypesupported) should be more specific about checking `type`, including generally requiring `codecs` [1], rejecting unrecognized parameters (e.g. 'Profiles' from RFC 6381), checking audio vs. video types, and determining whether multiple codecs (e.g. audio and video, if applicable) are supported together. The behavior for handling ambiguous codec strings, such as `avc1` without the avcoti, should also be clearly defined.

As an example, see how EME [handles MIME content type strings](https://w3c.github.io/encrypted-media/#get-supported-capabilities-for-audio-video-type).

[1] The codecs parameter is almost always necessary. There are few MIME types that specify the codec without the codecs parameter. One example is "audio/mpeg" for MP3.

**Comment by ddorwin** [comment]
The spec should similarly more clearly define how implementations should process `MediaRecorderOptions`'s [`mimeType`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorderoptions-mimetype) attribute. Perhaps they can share an algorithm.

FWIW, EME uses `contentType` to avoid ambiguity with a simple MIME type, such as `"video/mp4"`.

**Comment by jan-ivar** [comment]
This is no longer the recommended API for this. Closing in favor of https://www.w3.org/TR/media-capabilities/
