### ISSUE TITLE
Bugs in isTypeSupported() example

### ISSUE THREAD

**Issue by ddorwin** [w3c/mediacapture-record#94]
https://w3c.github.io/mediacapture-record/MediaRecorder.html#check-for-mediarecorder-and-mimetype.x has the following issues:
 1. "video/webm" and "audio/webm" only specify the container, which is insufficient and should not be allowed (see #92).
 1. `h264` is not a valid codec string. The correct string is `avc1` or `avc1.xxxxxx`. Probably prefer the latter - see item (2) in #93.
 1. The strings in the `codecs` sequence are content types, not codecs. The  `codecs` and  `codec` variables should be renamed

**Comment by yell0wd0g** [comment]
Regarding 1. ("video/webm"/"audio/webm" not being valid types) I think it's a strange situation since WebM has no recognised mime type in the [IANA list](http://www.iana.org/assignments/media-types/media-types.xhtml#video) (fun-fact: I requested it and got a negative reply) nor RFC IIRC, so I followed the guidelines in http://www.webmproject.org/docs/container/#canplaytype-function, namely:

> canPlayType(‘video/webm’) SHOULD return maybe
> canPlayType(‘audio/webm’) SHOULD return maybe
> canPlayType(‘video/webm; codecs=”vp8, vorbis”’) SHOULD return probably
...
> canPlayType(‘audio/webm; codecs=”opus”’) SHOULD return probably

which ended up in the strange situation that `video/webm` is OK. But I'd like to hear your take on all this.

Regarding 3. I'll wipe a correction, thanks!

**Comment by ddorwin** [comment]
I guess you need to decide on the meaning of a positive response from `isTypeSupported()`. Most likely, it should be used to find a value that can be successfully used for the `mimeType` member of `MediaRecorderOptions`. If so, the API should only allow sufficiently-specific types.

`canPlayType()` may not be a good guide, especially since it can return three values vs. the Boolean returned by `isTypeSupported()`. Note that `"maybe"` really just means the user agent can't not play it (it is not "[a type that the user agent knows it cannot render](https://html.spec.whatwg.org/multipage/embedded-content.html#dom-navigator-canplaytype)"). Since `isTypeSupported()` returns a Boolean (and because `"maybe"` has been confusing), it should be more certain when returning a positive result (e.g., "the user agent is confident that the type represents a media resource that it can" record).

Note: `canPlayType()` enables the application to walk a tree. (Is WebM supported? If so, is WebM with VP9 supported? If so, is WebM with VP9 and OPUS supported?...) In this case, checking just the container might be useful in determining all capabilities. However, for the purposes of determining whether a specific stream can be played, that is unnecessary.

**Comment by alvestrand** [comment]
webm is defined to have default codecs, which creates some issues for walking the tree.
ie if you probe for "video/webm", the mime type definition says that you need to return the same answer for "video/webm" as for "video/webm; codecs="vp8,vorbis"). There's no way to detect an implementation that  has broken the webm spec by supporting "video/webm; codecs="vp9,opus" and not "video/webm; codecs=vp8,vorbis".

Is this a problem with the WEBM definition, or a problem with the recording interface?

**Comment by ddorwin** [comment]
@alvestrand, where is this defined? Walking the tree was mostly theoretical, but I don't think implementations consider `"video/webm"` to be fully specified. For example, Chrome returns `"maybe"` rather than `"probably"` just as we do for `"video/mp4"`. "maybe" is also specified in the container guidelines referenced in https://github.com/w3c/mediacapture-record/issues/94#issuecomment-264611914.

I think the definition should be reevaluated, especially given conflicting information and implementations. Generic language like that referenced in #92 would avoid this being a problem with the recording interface (If `"video/webm"` is fully specified then it would be technically sufficient. However, as a practical matter, I would strongly encourage implementations of this API to treat is as not fully specified as appears to be the case for implementations of other APIs.)

**Comment by alvestrand** [comment]
Hm. It seems that someone's taken the definition away from where I thought it was.
This page:

https://www.webmproject.org/docs/container/

says you can walk the tree, while this page:

https://www.webmproject.org/about/faq/

used to say that VP8 and Orbis were the only codecs allowed, but now it says that VP9 and Opus are 
I think we should register the MIME type to keep ourselves from changing our minds without notice..

**Comment by yell0wd0g** [comment]
The [example](https://w3c.github.io/mediacapture-record/MediaRecorder.html#example1) ([codepen](https://codepen.io/miguelao/pen/edqNab?editors=0010)) reads now:
```
  var contentTypes = ["video/webm",
                      "video/webm;codecs=vp8",
                      "video/x-matroska;codecs=avc1",
                      "audio/webm",
                      "video/mp4;codecs=avc1",
                      "video/invalid"];
```

which corrects `h264` to `avc1`, corrects `video/webm;codecs=h264` to `video/webm;codecs=avc1`, etc.

Note that, as said elsewhere, `video/webm` is valid mime type for that format. I'm closing this issue since there's an array of others dealing with other subtleties (and linked from this issue's description).
