### ISSUE TITLE
Retroactive effect of isolation property change?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-record#97]
The text currently says:

"If at any point the stream's isolation properties change so that MediaRecorder is no longer allowed access to it, the UA must immediately stop gathering data, discard any data that it has gathered, and queue a task..."

This means that the event series:

start()
<half an hour passes>
<isolation properties change>

result in a recording of exactly nothing. This seems like it's going to surprise the user.
Why not flush the buffer when the isolation properties change?

**Comment by yell0wd0g** [comment]
From #108 :
> This homogenises the wording with the subsequent point that details what to do when recording can't continue for reasons other than isolation. In both cases: stop gathering data, fire an error event, send whatever has been encoded and fire an event called stop.

but we still have @foolip in #52 pointing out that the/an Error event should be the last one to be fired, which, I guess, applies to all cases.
