### ISSUE TITLE
UnknownError seems inappropriate

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-record#98]
The current spec says that if something happens to make recording stop, "UnknownError" must be fired at the recorder.

This seems like an odd choice. Why not "OperationError"?

**Comment by yell0wd0g** [comment]
These are the descriptions:
- [UnknownError](https://heycam.github.io/webidl/#unknownerror):
> The operation failed for an unknown transient reason (e.g. out of memory).

- [OperationError](https://heycam.github.io/webidl/#operationerror):
> The operation failed for an operation-specific reason.

Splitting hairs, really. I'd leave it as is.

FTR: Chrome returns `UnknownError` [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/mediarecorder/MediaRecorder.cpp?q=mediarecorder.cpp&sq=package:chromium&dr&l=223) on platform start error, whereas I don't see [FF](https://github.com/mozilla/gecko-dev/blob/master/dom/media/MediaRecorder.cpp#L1025) returning `UnknownError` at all (only `InvalidState` and `SecurityError`).

**Comment by yell0wd0g** [comment]
ping @alvestrand

**Comment by alvestrand** [comment]
OK, I'll leave it as is then.
