### ISSUE TITLE
ignoreMutedMedia on a combination of muted and unmuted tracks?

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-record#99]
If a stream contains two audio tracks, the "ignoreMutedMedia" flag is set, and one (and only one) track is muted, should recording of the other one continue or not?
At the moment, the text under the "start" method is unclear about this.

**Comment by yell0wd0g** [comment]
Will clarify.  Note that Gecko doesn't have this flag (@jesup, @jan-ivar): https://github.com/mozilla/gecko-dev/blob/86897859913403b68829dbf9a154f5a87c4b0638/dom/webidl/MediaRecorder.webidl

**Comment by jan-ivar** [comment]
Also, what's the behavior if I do this?
```js
let recorder = new MediaRecorder(stream);
setInterval(() => recorder.ignoreMutedMedia = !recorder.ignoreMutedMedia, 2000);
setInterval(() => stream.getTracks().forEach(t => t.enabled = !t.enabled), 3000);
```

**Comment by yell0wd0g** [comment]
The first repeating task will flip the value of `ignoreMutedMedia` from true to false. According to the current reading of the spec, MR will either ignore a muted track (`ignoreMutedMedia` == true) or insert blanks in the recording at the speed of the source (`ignoreMutedMedia` == false).

But, IIRC: `MediaStreamTrack.muted` is a read-only attribute that doesn't relate to `enabled` (*), so the second line doesn't affect the `muted` value, and so renders the behaviour of the lines @jan-ivar posted totally dependent on the behaviour of `stream` :smile:


(*) In [Chromium](https://cs.chromium.org/chromium/src/content/renderer/media/video_track_adapter.cc?sq=package:chromium&dr=CSs&rcl=1481717748&l=450), video `muted` state is updated by monitoring the amount of frames passing versus the frame rate.

https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-ignoremutedmedia

**Comment by jan-ivar** [comment]
(Note I forgot to add `rec.start();` to my example).

Hmm, was it really the intent of this spec to respect only the `muted` state and not the `enabled` state? Both do the same thing (inversely) - causing black/silence to be output - and differ only in that the former is out of control of the application. Seems like a mistake to me. What was the intent?

And my question is the same for `muted` state: What's the behavior if recording has started and a track vacillates between muted and unmuted say every 2 seconds? Does it get recorded or not?

Similarly, it's unclear to me from the spec what happens when flipping `ignoreMutedMedia` on and off during a recording of a stream with a muted track.

**Comment by yell0wd0g** [comment]
I'm not sure about what was the original intention of the Spec, or the status of the Media Capture and Streams at the time... 

But I replied to @alvestrand in the PR with an example that might clarify your questions; the hypothetical case was `if track A is recorded and track B is muted for 10 seconds with ignoreMutedMedia=true, will they then be 10 seconds out of sync?`:
> Every recorded video frame has a timestamp associated, if there is a jump in any of the sequences of timestamps, any player would just keep the last drawn canvas, unless, that is, ignoreMutedMedia inserts black video frames.
> 
> In the hypothetical case you mention, assuming A and B are video tracks for simplicity, after the muted hiatus in track B, they'll still be in sync, because the UA will still produce correct timestamps in the container. If you were playing both in parallel, then A will play all the way with no hiccups, whereas B will either be frozen for 10 seconds, or turn black for ten seconds, depending on ignoreMutedMedia.
>
> I'm not sure about the extent of enabled versus muted. In Chrome, muted is a reflection of no video passing by the track during a certain period of time; this being affected by enabled or not, depends on where the video flow is interrupted (before or after the Track). Maybe @guidou knows more?

**Comment by alvestrand** [comment]
So you're saying that "ignoremutedmedia" means "freeze the picture rather than displaying black".

Now, audio formats generally don't have timestamps, and there's no such thing as "frozen sound" (well, there is, in certain bug cases - it's a short loop and terribly annoying), so there should be silence - is the flag in reality only applicable for video?

**Comment by yell0wd0g** [comment]
> So you're saying that "ignoremutedmedia" means "freeze the picture rather than displaying black".

That's my interpretation/statement about the most likely behaviour to be found in media players :smile:.

> audio formats generally don't have timestamps

In a container, encoded audio is stored in packets, e.g. In Chrome ([Opus in Webm](https://cs.chromium.org/chromium/src/content/renderer/media/audio_track_recorder.cc?q=opus+60+audio+trackrecorder&sq=package:chromium&l=44&dr=C)) we split the incoming audio in 60ms sample sets, and each of those are encoded into a packet that has its own timestamp. The difference between consecutive audio packets' timestamps coming from the same audio Track should also be  60ms.

In the case of a muted audio source muted for a period of time, the sequence of encoded packets' timestamps will either jump (as much as the muted period length), or not (and the data will represent encoded silence), depending on `ignoreMutedMedia`. Why is this difference relevant to audio, I guess is a question for the media players.

**Comment by alvestrand** [comment]
Again: Do audio packets (in Matroska or MP3 files, for instance) have timestamps?
From the discussion, it seems that we might as well call the flag "freezeVideoOnMute".

**Comment by yell0wd0g** [comment]
> Do audio packets (in Matroska or MP3 files, for instance) have timestamps?

Quoting myself: `In a container, encoded audio is stored in packets`... `and each of those are encoded into a packet that has its own timestamp. ` You can see it in the libwebm interface [1]
So the answer is: *yes*.

Since all this has turned out to be confusing, I might add a small non-normative example with how a player might in all likelihood interpret the "jump" in the timestamp sequence.

If you want to rename the attribute, that's easy: it's not implemented neither in FF nor in Cr :smile:



[1]  https://cs.chromium.org/chromium/src/third_party/libwebm/source/mkvmuxer/mkvmuxer.cc?sq=package:chromium&dr=CSs&rcl=1481775657&l=3162

**Comment by jan-ivar** [comment]
Also, given how easy it is now to recompose streams out of tracks now, are we sure we still need this option? E.g. removing audio:

```js
let rec = new MediaRecorder(new MediaStream(stream.getVideoTracks()));
```

**Comment by yell0wd0g** [comment]
@jan-ivar, note that this flag only affects an active recording and the `muted` state of any input track.  If the amount of tracks of the input mediastream changes, that's a different topic (which falls under the non-normative [Even summary](https://w3c.github.io/mediacapture-record/MediaRecorder.html#event-summary) section, `ErrorEvent` entry:

> An error has occurred, e.g. out of memory or a modification to the stream has occurred that makes it impossible to continue recording (e.g. a Track has been added to or removed from the said stream while recording is occurring).

(if you disagree with the fact that recording MAY stop if tracks get added or removed, while that's fine, it's not pertaining to this Issue).

**Comment by jan-ivar** [comment]
@miguelao Is the common use case to flip this flag during recording? I thought that was more of an edge case, but I admit I have no idea what use case this feature serves to begin with.

**Comment by yell0wd0g** [comment]
@jan-ivar, I'm not sure what the intended use case was or is, @JimBarnett , @travisleithead who were the original spec writers might know more.

**Comment by alvestrand** [comment]
An easy fix is to delete it from the spec. We can always add it back later if an use case is found.

**Comment by yell0wd0g** [comment]
+1, if it's so hard to explain and is implemented nowhere, it's probably not worth it.

**Comment by marcusx2** [comment]
ignoreMutedMedia would be great if I have a sound in a game that sometimes is muted and sometimes is not...why is this feature obsolete?
